from rest_framework import serializers
from django.contrib.auth.models import User
from rest_framework.exceptions import ValidationError


from users.models import Confirm_User


class UserAuthoSerializer(serializers.Serializer):
    username = serializers.CharField()
    password = serializers.CharField()


class UserCreateSerializer(UserAuthoSerializer):
    email = serializers.EmailField()

    def validate_username(self, username):
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise ValidationError('User already is existed')


#
#



class ConfirmUserSerializer(serializers.Serializer):
    user_id = serializers.IntegerField()
    code = serializers.CharField(min_length=6, max_length=6)

    def validate_user_id(self, user_id):
        try:
            Confirm_User.objects.get(id=user_id)
        except Confirm_User.DoesNotExist:
            return user_id
        raise ValidationError("User_id does not exists!")